#Variables
network:
  namespace: monitoring

#Node
node:
  worker: docker-desktop

#Tech
tech:
  memory: 500Mi
  cpu: 250m

# Prometheus
prometheus:
  replicaCount: 1
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.24.0
  port: 9090
  scrapeInterval: 10s
  evaluationInterval: 10s
  retention: 30d

# Grafana
grafana:
  author: "Dmitrii-Sakhno"
  enabled: true
  image:
    repository: grafana/grafana
    tag: 7.3.5
  port: 3000
  adminPassword: "admin"
  dataSource:
    type: prometheus
    url: http://prometheus:9090

# Persistent Volume
persistentVolume:
  enabled: true
  size: 1Gi
  mountPath: /var/lib/grafana
