apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Release.Name }}-pv-alertmanager
    namespace: {{ .Values.network.namespace }}
spec:
    capacity:
        storage: {{ .Values.persistentVolume.size }}
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    local:
        path: /run/desktop/mnt/host/c/test-3
    storageClassName: local-storage-3
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - {{ .Values.node.worker }}