apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc-prometheus
    namespace: {{ .Values.network.namespace }}
spec:
    selector:
        app: {{ .Release.Name }}-prometheus
    ports:
    - name: http
      port: 9090
      targetPort: 9090
    type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-svc-grafana
    namespace: {{ .Values.network.namespace }}
spec:
    selector:
        app: {{ .Release.Name }}-grafana
    ports:
    - name: http
      port: 3000
      targetPort: 3000
    type: ClusterIP